export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  column: [
    {
      label: "主键ID",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "租户ID",
      prop: "tenantId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "状态：PROCESSING处理中 FINISHED已完成",
      prop: "status",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否删除",
      prop: "isDeleted",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "媒体状态：NORMAL正常 DISABLED禁用",
      prop: "mediaStatus",
      type: "select",
      dicUrl: "/blade-system/dict/dictionary?code=media_status",
      dataType: "number",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "邀约ID",
      prop: "inviteId",
      type: "input",
    },
    {
      label: "媒体地址",
      prop: "mediaUrl",
      type: "input",
    },
    {
      label: "媒体类型：IMAGE图片",
      prop: "mediaType",
      type: "input",
      dicUrl: "/blade-system/dict/dictionary?code=media_type",
      dataType: "number",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "排序",
      prop: "sortNo",
      type: "input",
    },
  ]
}
