export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  column: [
    {
      label: "主键ID",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "租户ID",
      prop: "tenantId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "状态：PROCESSING处理中 FINISHED已完成",
      prop: "status",
      type: "select",
      dicUrl: "/blade-system/dict/dictionary?code=sport_invite_status",
      dataType: "number",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否删除",
      prop: "isDeleted",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "邀约ID",
      prop: "inviteId",
      type: "input",
    },
    {
      label: "申请ID",
      prop: "applyId",
      type: "input",
    },
    {
      label: "审核人ID",
      prop: "auditUserId",
      type: "input",
    },
    {
      label: "审核动作：APPROVE通过 REJECT拒绝",
      prop: "auditAction",
      type: "select",
      dicUrl: "/blade-system/dict/dictionary?code=audit_action",
      dataType: "number",
      props: {
        label: "dictValue",
        value: "dictKey"
      },
    },
    {
      label: "审核备注",
      prop: "auditRemark",
      type: "input",
    },
  ]
}
